sudo: required
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
    

script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
addons:
  sonarcloud:
    organization: "richard-w-parry-github" 