spring:
  profiles: 
    active:
    - local

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./database/estate-agent;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: 
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    enabled: false